API for bovine-inventory
========================
Shaun Smiley <senorsmile@gmail.com>
v2.0.0, 2016-12
:imagesdir: images
:toc: preamble

Detailed description of api docs here!

Search
-----
[nested]
* Search for host or group. Specify type as group, host, or any.
+
[source]
....
GET /api/search?type=any&name=web_hosts
....
** Example results:
+
[source,json]
----
{
  "status": "success",
  "code": 200,
  "data": {
  "groups": [
    "webhosts1",
    "webhosts2"
    ],
  "hosts": [
   "webhost1"
   "webhost2"
  ]
}
----

Hostvars
--------

[nested]
* Retrieve a host and it's vars
+
[source]
....
GET /api/hostvars?name=host1
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "code": 200,
  "data": {
  "parent_group": "group1",
  "host": "host1",
  "vars": {
    "foo": "bar",
    "var": "1"
    }
  }
}
----

* Retrieve a specific variable for a host
+
[source]
....
GET /api/hostvars?name=host1&var=foo
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "code": 200,
  "data": {
  "host": "host1",
  "vars": {
    "foo": "bar",
    }
  }
}
----

* Add a new host
+
[source]
....
POST /api/hostvars?name=newhostname
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 201
}
----
* Update or add a new var to a host.
This call is idempotent, so if a value already matches no changes will be made.
+
[source]
....
PUT /api/hostvars?name=newhostname&var1=1
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 200
}
----


* Delete a host
[source]
....
DELETE /api/hostvars?name=name_of_the_host
....

Groups
-----

[nested]
* Get a group.
+
[source]
....
GET /api/groupvars?name=group_name
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 200,
  "data": {
    "group_name": "group1",
    "parent_group": "all",
    "hosts": [
      "host1",
      "host2",
      "host2"
    ],
    "vars" : {
      "var1": 1,
      "var2": 2
    }
  }
}
----

Get top level groups
--------------------

[nested]
[source]
....
GET /api/top_level_groups
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 200,
  "data": [
    "webhosts",
    "db_server",
    "logs",
  ]
}
----

Specify api version
-------------------

[nested]
* Currently, only v2.0 of this api is available.
As new versions come out, we will strive for backward compatibility, and
will always "attempt" to support previous versions of the api.
* List all with api version
+
[source]
....
/api/group/list?api_version=2.0
....
