API for bovine-inventory
========================
Shaun Smiley <senorsmile@gmail.com>
v2.0.0, 2016-12
:imagesdir: images
:toc: preamble

Detailed description of api docs here!

GET Search
----------
[nested]
* Search for host or group.
Specify type as  a group, host, or any to limit the search.
+
[source]
....
GET /api/search?type=any&name=web
....
** Example results:
+
[source,json]
----
{
  "status": "success",
  "data": {
  "groups": [
    "webhosts1",
    "webhosts2"
    ],
  "hosts": [
   "webhost1"
   "webhost2"
  ]
}
----
** HTTP response code: 200

GET Hostvars
------------

[nested]
* Retrieve a host and it's vars.
+
[source]
....
GET /api/hostvars?name=host1
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "data": {
    "parent_groups": [
      "group1",
    ]
    "host": "host1",
    "vars": {
      "foo": "bar",
      "var": "1"
      }
    }
}
----
** HTTP response code: 200

* Retrieve a specific variable for that host.
+
[source]
....
GET /api/hostvars?name=host1&var=foo
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "data": {
    "host": "host1",
    "vars": {
      "foo": "bar",
      }
    }
}
----
** HTTP response code: 200

* Add a new host
+
[source]
....
POST /api/hostvars?name=newhostname
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
}
----
** HTTP response code: 200
* Update or add a new var to a host.
This call is idempotent, so if a value already matches no changes will be made.
+
[source]
....
PUT /api/hostvars?name=newhostname&var1=1
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
}
----
** HTTP response code: 200


* Delete a host
[source]
....
DELETE /api/hostvars?name=name_of_the_host
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
}
----
** HTTP response code: 204

GET Groups
---------

[nested]
* Get a group.
+
[source]
....
GET /api/groupvars?name=group_name
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "data": {
    "group_name": "group1",
    "parent_groups": [
      "group2",
      "group3"
    ],
    "hosts": [
      "host1",
      "host2",
      "host2"
    ],
    "vars" : {
      "var1": 1,
      "var2": 2
    },
    "children": [
      "group6",
      "group20"
    ],
  }
}
----
** HTTP response code: 200

Get top level groups
--------------------

[nested]
[source]
....
GET /api/top_level_groups
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "data": [
    "webhosts",
    "db_server",
    "logs",
  ]
}
----
** HTTP response code: 200

Specify api version
-------------------

[nested]
* Currently, only v2.0 of this api is available.
As new versions come out, we will strive for backward compatibility, and
will always "attempt" to support previous versions of the api.
* List all with api version
+
[source]
....
GET /api/search?api_version=2.0
....

Misc
----

[nested]
* Requesting a missing host or group will come back with a 404.
** Example response:
+
[source,json]
----
{
  "status": "fail",
  "data": {"host_name": "Host/group is not available"}
}
----
** HTTP response code: 404
* Invalid requests will also come back with failure.
** Example response:
+
[source,json]
----
{
  "status": "fail",
  "data": {"name": "group or a host host name is required"}
}
----
** HTTP response code: 400
* Top level groups can not deleted without all the child groups or hosts being removed.
