API for bovine-inventory
========================
Shaun Smiley <senorsmile@gmail.com>
v2.0.0, 2016-12
:imagesdir: images
:toc: preamble

Detailed description of api docs here!

Search
-----
[nested]
* Search for host or group
+
[source]
....
GET /api/search?type=any&name=web_hosts
....
** Example results:
+
[source,json]
----
{
  "status": "success",
  "data": [
   "host1",
   "host2",
   "webhost1"
  ]
}
----

Hostvars
--------

[nested]
* Retrieve a host and it's vars
+
[source]
....
GET /api/hostvars?name=host1
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "data": {
  "host": "host1",
  "vars": {
    "foo": "bar",
    "var": "1"
    }
  }
}
----

* Retrieve a specific hosts and a specific variable
+
[source]
....
GET /api/hostvars?name=host1&var=foo
....
** Example results:
+
[source,json]
----
{
  "status": "successful",
  "data": {
  "host": "host1",
  "vars": {
    "foo": "bar",
    }
  }
}
----

* Add a new host
+
[source]
....
POST /api/hostvars?name=newhostname
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 201
}
----
* Update or add a new var to a host. If the variable is already present it will update it's value. If value already matches nothing will happen
+
[source]
....
PUT /api/hostvars?name=newhostname&var1=1
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 200
}
----


* Delete a host
[source]
....
DELETE /api/hostvars?name=name_of_the_host
....

Groups
-----

[nested]
* All groups
+
[source]
....
GET /api/groupvars?name=group_name
....

Get top level groups
--------------------

[nested]
[source]
....
GET /api/top_level_groups
....
** Example response:
+
[source,json]
----
{
  "status": "successful",
  "code": 200
}
----

Specify api version
-------------------

[nested]
* Currently, only v2.0 of this api is available.
As new versions come out, we will strive for backward compatibility, and
will always "attempt" to support previous versions of the api.
* List all with api version
+
[source]
....
/api/group/list?api_version=2.0
....
